title: Jack of all spades
author: Picibucor
email: pibu@kgb.hu
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  My awesome description is now provided :D

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
